import { useState, type FormEvent } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { BadgeDollarSign, Plus, UserRoundCheck, X } from 'lucide-react';
import {
  createAffiliate,
  listAffiliates,
  listCommissionEntries,
  listCommissionSummary,
  recordCommissionPayout,
  updateAffiliateStatus,
} from '../../services/controlApi';
import { useAuthStore } from '../../store/authStore';
import { useProductStore } from '../../store/productStore';

export function Affiliates() {
  const application = useProductStore((state) => state.selectedProduct);
  const isOwner = useAuthStore((state) => state.user?.role === 'owner');
  const queryClient = useQueryClient();
  const [selectedId, setSelectedId] = useState<string | null>(null);
  const [showCreate, setShowCreate] = useState(false);
  const [showPayout, setShowPayout] = useState(false);
  const [affiliateForm, setAffiliateForm] = useState({ contact_name: '', company_name: '', email: '', mobile_number: '' });
  const [payoutForm, setPayoutForm] = useState({ amount: '', currency: 'INR', reference: '', notes: '' });
  const affiliates = useQuery({ queryKey: ['affiliates', application?.id], queryFn: () => listAffiliates(application!.id), enabled: Boolean(application) });
  const activeAffiliateId = selectedId ?? affiliates.data?.[0]?.id ?? null;
  const summary = useQuery({ queryKey: ['affiliate-summary', application?.id, activeAffiliateId], queryFn: () => listCommissionSummary(application!.id, activeAffiliateId!), enabled: Boolean(application && activeAffiliateId) });
  const entries = useQuery({ queryKey: ['affiliate-entries', application?.id, activeAffiliateId], queryFn: () => listCommissionEntries(application!.id, activeAffiliateId!), enabled: Boolean(application && activeAffiliateId) });
  const createMutation = useMutation({ mutationFn: () => createAffiliate(application!.id, { ...affiliateForm, company_name: affiliateForm.company_name || undefined, mobile_number: affiliateForm.mobile_number || undefined }), onSuccess: async (created) => { setShowCreate(false); setSelectedId(created.id); setAffiliateForm({ contact_name: '', company_name: '', email: '', mobile_number: '' }); await queryClient.invalidateQueries({ queryKey: ['affiliates', application?.id] }); } });
  const statusMutation = useMutation({ mutationFn: ({ id, status }: { id: string; status: 'active' | 'disabled' }) => updateAffiliateStatus(application!.id, id, status), onSuccess: () => queryClient.invalidateQueries({ queryKey: ['affiliates', application?.id] }) });
  const payoutMutation = useMutation({ mutationFn: () => recordCommissionPayout(application!.id, activeAffiliateId!, payoutForm), onSuccess: async () => { setShowPayout(false); setPayoutForm({ amount: '', currency: 'INR', reference: '', notes: '' }); await Promise.all([queryClient.invalidateQueries({ queryKey: ['affiliate-summary', application?.id, activeAffiliateId] }), queryClient.invalidateQueries({ queryKey: ['affiliate-entries', application?.id, activeAffiliateId] })]); } });
  if (!application) return null;
  const selected = affiliates.data?.find((item) => item.id === activeAffiliateId);

  return <div className="mx-auto max-w-7xl space-y-6">
    <header className="flex items-end justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[0.2em] text-blue-400">{application.displayName}</p><h1 className="mt-2 text-3xl font-bold">Affiliates</h1><p className="mt-2 text-slate-400">Partners, referral coupons, earned commission and payout history.</p></div>{isOwner && <button onClick={() => setShowCreate(true)} className="rounded-lg bg-blue-600 px-4 py-2 text-sm font-semibold"><Plus className="mr-2 inline h-4 w-4" />New affiliate</button>}</header>
    {affiliates.isError && <div className="rounded-xl border border-red-500/20 bg-red-500/10 p-4 text-red-300">Unable to load scoped affiliates.</div>}
    <div className="grid gap-6 lg:grid-cols-[340px_1fr]"><div className="space-y-3">{affiliates.data?.map((affiliate) => <button key={affiliate.id} onClick={() => setSelectedId(affiliate.id)} className={`w-full rounded-2xl border p-4 text-left transition ${selectedId === affiliate.id ? 'border-blue-500 bg-blue-500/10' : 'border-slate-800 bg-slate-900/60 hover:border-slate-700'}`}><div className="flex items-start justify-between"><UserRoundCheck className="h-5 w-5 text-blue-400" /><span className={`text-xs font-semibold capitalize ${affiliate.status === 'active' ? 'text-emerald-400' : 'text-amber-400'}`}>{affiliate.status}</span></div><h2 className="mt-3 font-semibold">{affiliate.contact_name}</h2><p className="mt-1 text-sm text-slate-400">{affiliate.company_name || affiliate.email}</p></button>)}{affiliates.data?.length === 0 && <div className="rounded-2xl border border-dashed border-slate-700 p-6 text-center text-sm text-slate-500">No affiliates yet.</div>}</div>
      <section className="rounded-2xl border border-slate-800 bg-slate-900/60 p-6">{selected ? <><div className="flex flex-wrap items-start justify-between gap-4"><div><h2 className="text-xl font-semibold">{selected.contact_name}</h2><p className="mt-1 text-sm text-slate-400">{selected.email}{selected.company_name && ` · ${selected.company_name}`}</p></div>{isOwner && <div className="flex gap-2"><button onClick={() => statusMutation.mutate({ id: selected.id, status: selected.status === 'active' ? 'disabled' : 'active' })} className="rounded-lg border border-slate-700 px-3 py-2 text-sm">{selected.status === 'active' ? 'Disable' : 'Enable'}</button><button onClick={() => setShowPayout(true)} className="rounded-lg bg-emerald-600 px-3 py-2 text-sm font-semibold"><BadgeDollarSign className="mr-1 inline h-4 w-4" />Record payout</button></div>}</div><div className="mt-6 grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{summary.data?.map((item) => <div key={item.currency} className="rounded-xl border border-slate-800 bg-slate-950/60 p-4"><p className="text-xs uppercase text-slate-500">{item.currency} balance</p><p className="mt-2 text-xl font-bold">{item.currency} {Number(item.balance).toLocaleString()}</p><p className="mt-2 text-xs text-slate-500">Earned {item.earned} · Paid {item.paid}</p></div>)}{summary.data?.length === 0 && <div className="text-sm text-slate-500">No commission has been earned.</div>}</div><h3 className="mt-8 font-semibold">Commission ledger</h3><div className="mt-3 divide-y divide-slate-800">{entries.data?.map((entry) => <div key={entry.id} className="flex items-center justify-between gap-4 py-3 text-sm"><div><p className="capitalize">{entry.entry_type}</p><p className="mt-1 font-mono text-xs text-slate-500">{entry.reference}</p></div><div className="text-right"><p className={entry.entry_type === 'paid' ? 'text-amber-300' : 'text-emerald-300'}>{entry.currency} {entry.amount}</p><p className="mt-1 text-xs text-slate-500">{new Date(entry.occurred_at).toLocaleDateString()}</p></div></div>)}{entries.data?.length === 0 && <p className="py-5 text-sm text-slate-500">No ledger entries.</p>}</div></> : <div className="grid min-h-64 place-items-center text-slate-500">Select an affiliate.</div>}</section></div>
    {showCreate && <div className="fixed inset-0 z-50 grid place-items-center bg-black/70 p-4"><form onSubmit={(event: FormEvent) => { event.preventDefault(); createMutation.mutate(); }} className="w-full max-w-lg rounded-2xl border border-slate-700 bg-slate-900 p-6"><div className="flex justify-between"><h2 className="text-xl font-semibold">Add affiliate</h2><button type="button" onClick={() => setShowCreate(false)}><X className="h-5 w-5" /></button></div><div className="mt-5 grid gap-4"><label className="text-sm">Contact name<input required value={affiliateForm.contact_name} onChange={(event) => setAffiliateForm({ ...affiliateForm, contact_name: event.target.value })} className="mt-1 w-full rounded-lg border border-slate-700 bg-slate-950 p-2.5" /></label><label className="text-sm">Email<input required type="email" value={affiliateForm.email} onChange={(event) => setAffiliateForm({ ...affiliateForm, email: event.target.value })} className="mt-1 w-full rounded-lg border border-slate-700 bg-slate-950 p-2.5" /></label><label className="text-sm">Company<input value={affiliateForm.company_name} onChange={(event) => setAffiliateForm({ ...affiliateForm, company_name: event.target.value })} className="mt-1 w-full rounded-lg border border-slate-700 bg-slate-950 p-2.5" /></label><label className="text-sm">Mobile<input value={affiliateForm.mobile_number} onChange={(event) => setAffiliateForm({ ...affiliateForm, mobile_number: event.target.value })} className="mt-1 w-full rounded-lg border border-slate-700 bg-slate-950 p-2.5" /></label></div>{createMutation.isError && <p className="mt-4 text-sm text-red-300">Unable to create affiliate. The email may already exist.</p>}<button className="mt-6 w-full rounded-lg bg-blue-600 py-3 text-sm font-semibold">Create affiliate</button></form></div>}
    {showPayout && selected && <div className="fixed inset-0 z-50 grid place-items-center bg-black/70 p-4"><form onSubmit={(event: FormEvent) => { event.preventDefault(); payoutMutation.mutate(); }} className="w-full max-w-lg rounded-2xl border border-slate-700 bg-slate-900 p-6"><div className="flex justify-between"><h2 className="text-xl font-semibold">Record commission payout</h2><button type="button" onClick={() => setShowPayout(false)}><X className="h-5 w-5" /></button></div><div className="mt-5 grid gap-4"><label className="text-sm">Amount<input required min="0.01" step="0.01" type="number" value={payoutForm.amount} onChange={(event) => setPayoutForm({ ...payoutForm, amount: event.target.value })} className="mt-1 w-full rounded-lg border border-slate-700 bg-slate-950 p-2.5" /></label><label className="text-sm">Currency<input required maxLength={3} value={payoutForm.currency} onChange={(event) => setPayoutForm({ ...payoutForm, currency: event.target.value.toUpperCase() })} className="mt-1 w-full rounded-lg border border-slate-700 bg-slate-950 p-2.5 uppercase" /></label><label className="text-sm">Payment reference<input required minLength={8} value={payoutForm.reference} onChange={(event) => setPayoutForm({ ...payoutForm, reference: event.target.value })} className="mt-1 w-full rounded-lg border border-slate-700 bg-slate-950 p-2.5 font-mono" /></label><label className="text-sm">Notes<input value={payoutForm.notes} onChange={(event) => setPayoutForm({ ...payoutForm, notes: event.target.value })} className="mt-1 w-full rounded-lg border border-slate-700 bg-slate-950 p-2.5" /></label></div>{payoutMutation.isError && <p className="mt-4 text-sm text-red-300">Payout failed. It cannot exceed the available balance and its reference must be unique.</p>}<button className="mt-6 w-full rounded-lg bg-emerald-600 py-3 text-sm font-semibold">Record payout</button></form></div>}
  </div>;
}
