import { useState, type FormEvent } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { BellRing, Plus, Send, X } from 'lucide-react';
import {
  cancelNotification,
  createNotification,
  dispatchNotification,
  listNotifications,
  listPlans,
} from '../../services/controlApi';
import { useAuthStore } from '../../store/authStore';
import { useProductStore } from '../../store/productStore';

export function Notifications() {
  const application = useProductStore((state) => state.selectedProduct);
  const isOwner = useAuthStore((state) => state.user?.role === 'owner');
  const queryClient = useQueryClient();
  const [showForm, setShowForm] = useState(false);
  const [dispatchResult, setDispatchResult] = useState<string | null>(null);
  const [form, setForm] = useState({ title: '', message: '', deep_link: '', audience_type: 'all_subscribers' as 'all_subscribers' | 'plans', plan_ids: [] as string[], scheduled: false, scheduled_at: '' });
  const notifications = useQuery({ queryKey: ['notifications', application?.id], queryFn: () => listNotifications(application!.id), enabled: Boolean(application) });
  const plans = useQuery({ queryKey: ['plans', application?.id], queryFn: () => listPlans(application!.id), enabled: Boolean(application) });
  const refresh = () => queryClient.invalidateQueries({ queryKey: ['notifications', application?.id] });
  const createMutation = useMutation({ mutationFn: () => createNotification(application!.id, { title: form.title, message: form.message, deep_link: form.deep_link || undefined, action_metadata: {}, audience_type: form.audience_type, plan_ids: form.audience_type === 'plans' ? form.plan_ids : [], status: form.scheduled ? 'scheduled' : 'draft', scheduled_at: form.scheduled ? new Date(form.scheduled_at).toISOString() : undefined }), onSuccess: async () => { setShowForm(false); setForm({ title: '', message: '', deep_link: '', audience_type: 'all_subscribers', plan_ids: [], scheduled: false, scheduled_at: '' }); await refresh(); } });
  const dispatchMutation = useMutation({ mutationFn: (id: string) => dispatchNotification(application!.id, id), onSuccess: async (result) => { setDispatchResult(`${result.recipient_count} recipient${result.recipient_count === 1 ? '' : 's'} queued`); await refresh(); } });
  const cancelMutation = useMutation({ mutationFn: (id: string) => cancelNotification(application!.id, id), onSuccess: refresh });
  if (!application) return null;
  const planNames = new Map(plans.data?.map((plan) => [plan.id, plan.name]) ?? []);
  const submit = (event: FormEvent) => { event.preventDefault(); createMutation.mutate(); };
  const togglePlan = (id: string) => setForm((value) => ({ ...value, plan_ids: value.plan_ids.includes(id) ? value.plan_ids.filter((item) => item !== id) : [...value.plan_ids, id] }));

  return <div className="mx-auto max-w-6xl space-y-6">
    <header className="flex items-end justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[0.2em] text-blue-400">{application.displayName}</p><h1 className="mt-2 text-3xl font-bold">Push notifications</h1><p className="mt-2 text-slate-400">Durable, app-scoped subscriber messaging through the application adapter.</p></div>{isOwner && <button onClick={() => setShowForm(true)} className="rounded-lg bg-blue-600 px-4 py-2 text-sm font-semibold"><Plus className="mr-2 inline h-4 w-4" />Compose</button>}</header>
    {dispatchResult && <div className="rounded-xl border border-emerald-500/20 bg-emerald-500/10 p-3 text-sm text-emerald-300">{dispatchResult}</div>}
    {notifications.isError && <div className="rounded-xl border border-red-500/20 bg-red-500/10 p-4 text-red-300">Unable to load notifications.</div>}
    <div className="space-y-4">{notifications.data?.map((notification) => <article key={notification.id} className="rounded-2xl border border-slate-800 bg-slate-900/60 p-5"><div className="flex flex-wrap items-start justify-between gap-4"><div className="flex gap-4"><span className="grid h-11 w-11 shrink-0 place-items-center rounded-xl bg-sky-500/10 text-sky-400"><BellRing className="h-5 w-5" /></span><div><h2 className="font-semibold">{notification.title}</h2><p className="mt-2 max-w-2xl text-sm text-slate-400">{notification.message}</p><p className="mt-3 text-xs text-slate-500">{notification.audience_type === 'all_subscribers' ? 'All active subscribers' : notification.plan_ids.map((id) => planNames.get(id) ?? id).join(', ')}{notification.scheduled_at && ` · ${new Date(notification.scheduled_at).toLocaleString()}`}</p></div></div><div className="flex items-center gap-2"><span className="rounded-full bg-slate-800 px-3 py-1 text-xs font-semibold capitalize">{notification.status}</span>{isOwner && ['draft', 'scheduled'].includes(notification.status) && <><button onClick={() => dispatchMutation.mutate(notification.id)} className="rounded-lg bg-blue-600 px-3 py-2 text-xs font-semibold"><Send className="mr-1 inline h-3.5 w-3.5" />Send now</button><button onClick={() => cancelMutation.mutate(notification.id)} className="rounded-lg border border-slate-700 px-3 py-2 text-xs">Cancel</button></>}</div></div></article>)}{notifications.data?.length === 0 && <div className="rounded-2xl border border-dashed border-slate-700 p-8 text-center text-slate-500">No notifications composed for this application.</div>}</div>
    {showForm && <div className="fixed inset-0 z-50 grid place-items-center overflow-y-auto bg-black/70 p-4"><form onSubmit={submit} className="my-8 w-full max-w-xl rounded-2xl border border-slate-700 bg-slate-900 p-6"><div className="flex justify-between"><h2 className="text-xl font-semibold">Compose notification</h2><button type="button" onClick={() => setShowForm(false)}><X className="h-5 w-5" /></button></div><div className="mt-5 grid gap-4"><label className="text-sm">Title<input required maxLength={200} value={form.title} onChange={(event) => setForm({ ...form, title: event.target.value })} className="mt-1 w-full rounded-lg border border-slate-700 bg-slate-950 p-2.5" /></label><label className="text-sm">Message<textarea required rows={4} value={form.message} onChange={(event) => setForm({ ...form, message: event.target.value })} className="mt-1 w-full rounded-lg border border-slate-700 bg-slate-950 p-2.5" /></label><label className="text-sm">Application deep link (optional)<input placeholder="/invoices" value={form.deep_link} onChange={(event) => setForm({ ...form, deep_link: event.target.value })} className="mt-1 w-full rounded-lg border border-slate-700 bg-slate-950 p-2.5 font-mono" /></label><label className="text-sm">Audience<select value={form.audience_type} onChange={(event) => setForm({ ...form, audience_type: event.target.value as 'all_subscribers' | 'plans' })} className="mt-1 w-full rounded-lg border border-slate-700 bg-slate-950 p-2.5"><option value="all_subscribers">All active subscribers</option><option value="plans">Selected plans</option></select></label>{form.audience_type === 'plans' && <fieldset><legend className="text-sm">Plans</legend><div className="mt-2 grid gap-2 sm:grid-cols-2">{plans.data?.map((plan) => <label key={plan.id} className="flex items-center gap-2 rounded-lg border border-slate-800 p-2 text-sm"><input type="checkbox" checked={form.plan_ids.includes(plan.id)} onChange={() => togglePlan(plan.id)} />{plan.name}</label>)}</div></fieldset>}<label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={form.scheduled} onChange={(event) => setForm({ ...form, scheduled: event.target.checked })} />Schedule for later</label>{form.scheduled && <label className="text-sm">Schedule time<input required type="datetime-local" value={form.scheduled_at} onChange={(event) => setForm({ ...form, scheduled_at: event.target.value })} className="mt-1 w-full rounded-lg border border-slate-700 bg-slate-950 p-2.5" /></label>}</div>{createMutation.isError && <p className="mt-4 text-sm text-red-300">Could not save notification. Check the audience, schedule and deep link.</p>}<button disabled={form.audience_type === 'plans' && !form.plan_ids.length} className="mt-6 w-full rounded-lg bg-blue-600 py-3 text-sm font-semibold disabled:opacity-40">Save notification</button></form></div>}
  </div>;
}
