import { useState, type FormEvent } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { Activity, Copy, KeyRound, Save, Store } from 'lucide-react';
import {
  getPlanUiSettings,
  listCredentials,
  listHealthReports,
  listPlans,
  rotateCredential,
  updateApplicationSettings,
  updatePlanUiSettings,
} from '../../services/controlApi';
import { useProductStore } from '../../store/productStore';

export function Settings() {
  const application = useProductStore((state) => state.selectedProduct);
  const setProducts = useProductStore((state) => state.setProducts);
  const products = useProductStore((state) => state.products);
  const queryClient = useQueryClient();
  const [issuedSecret, setIssuedSecret] = useState<string | null>(null);
  const [general, setGeneral] = useState(() => ({ name: application?.displayName ?? '', frontend_url: application?.frontendUrl ?? '', control_api_base_url: application?.apiBaseUrl ?? '', health_path: application?.healthPath ?? '/control/v1/health', environment: application?.environment ?? 'development' as const }));
  const credentials = useQuery({ queryKey: ['credentials', application?.id], queryFn: () => listCredentials(application!.id), enabled: Boolean(application) });
  const health = useQuery({ queryKey: ['health-reports', application?.id], queryFn: () => listHealthReports(application!.id), enabled: Boolean(application) });
  const plans = useQuery({ queryKey: ['plans', application?.id], queryFn: () => listPlans(application!.id), enabled: Boolean(application) });
  const planUi = useQuery({ queryKey: ['plan-ui', application?.id], queryFn: () => getPlanUiSettings(application!.id), enabled: Boolean(application) });
  const generalMutation = useMutation({ mutationFn: () => updateApplicationSettings(application!.id, { ...general, frontend_url: general.frontend_url || undefined }), onSuccess: (updated) => { setProducts(products.map((item) => item.id === updated.id ? updated : item)); } });
  const rotateMutation = useMutation({ mutationFn: () => rotateCredential(application!.id, 24), onSuccess: async (credential) => { setIssuedSecret(credential.secret); await queryClient.invalidateQueries({ queryKey: ['credentials', application?.id] }); } });
  const storefrontMutation = useMutation({ mutationFn: () => updatePlanUiSettings(application!.id, { recommended_plan_id: planUi.data?.recommended_plan_id ?? null, show_feature_comparison: planUi.data?.show_feature_comparison ?? true, show_billing_period_selector: planUi.data?.show_billing_period_selector ?? true, display_labels: planUi.data?.display_labels ?? {}, items: (plans.data ?? []).map((plan, index) => { const current = planUi.data?.items.find((item) => item.plan_id === plan.id); return { plan_id: plan.id, visible: current?.visible ?? true, display_order: index, display_label: current?.display_label ?? null }; }) }), onSuccess: () => queryClient.invalidateQueries({ queryKey: ['plan-ui', application?.id] }) });
  if (!application) return null;
  const latestHealth = health.data?.[0];
  const submitGeneral = (event: FormEvent) => { event.preventDefault(); generalMutation.mutate(); };

  return <div className="mx-auto max-w-6xl space-y-6">
    <header><p className="text-xs font-bold uppercase tracking-[0.2em] text-blue-400">{application.displayName}</p><h1 className="mt-2 text-3xl font-bold">Settings</h1><p className="mt-2 text-slate-400">Application integration, health, credentials and subscription presentation.</p></header>
    <div className="grid gap-6 lg:grid-cols-2"><form onSubmit={submitGeneral} className="rounded-2xl border border-slate-800 bg-slate-900/60 p-6"><h2 className="flex items-center gap-2 font-semibold"><Save className="h-5 w-5 text-blue-400" />General integration</h2><div className="mt-5 grid gap-4"><label className="text-sm">Display name<input required value={general.name} onChange={(event) => setGeneral({ ...general, name: event.target.value })} className="mt-1 w-full rounded-lg border border-slate-700 bg-slate-950 p-2.5" /></label><label className="text-sm">Frontend URL<input type="url" value={general.frontend_url} onChange={(event) => setGeneral({ ...general, frontend_url: event.target.value })} className="mt-1 w-full rounded-lg border border-slate-700 bg-slate-950 p-2.5 font-mono" /></label><label className="text-sm">Control API URL<input required type="url" value={general.control_api_base_url} onChange={(event) => setGeneral({ ...general, control_api_base_url: event.target.value })} className="mt-1 w-full rounded-lg border border-slate-700 bg-slate-950 p-2.5 font-mono" /></label><label className="text-sm">Health path<input required value={general.health_path} onChange={(event) => setGeneral({ ...general, health_path: event.target.value })} className="mt-1 w-full rounded-lg border border-slate-700 bg-slate-950 p-2.5 font-mono" /></label></div>{generalMutation.isError && <p className="mt-3 text-sm text-red-300">Settings were rejected. Production URLs require public HTTPS endpoints.</p>}<button className="mt-5 rounded-lg bg-blue-600 px-4 py-2 text-sm font-semibold">Save settings</button></form>
      <section className="rounded-2xl border border-slate-800 bg-slate-900/60 p-6"><h2 className="flex items-center gap-2 font-semibold"><Activity className="h-5 w-5 text-emerald-400" />Application health</h2>{latestHealth ? <div className="mt-5"><p className="text-2xl font-bold capitalize">{latestHealth.overall_status}</p><p className="mt-1 text-sm text-slate-500">Reported {new Date(latestHealth.checked_at).toLocaleString()}</p><div className="mt-4 grid grid-cols-3 gap-2 text-center text-xs"><span className="rounded-lg bg-slate-950 p-3">Frontend<br/><b className="capitalize">{latestHealth.frontend_status}</b></span><span className="rounded-lg bg-slate-950 p-3">Backend<br/><b className="capitalize">{latestHealth.backend_status}</b></span><span className="rounded-lg bg-slate-950 p-3">Database<br/><b className="capitalize">{latestHealth.database_status}</b></span></div>{latestHealth.incident_summary && <p className="mt-4 text-sm text-amber-300">{latestHealth.incident_summary}</p>}</div> : <p className="mt-5 text-sm text-slate-500">Awaiting the first authenticated health report from the application adapter.</p>}</section>
      <section className="rounded-2xl border border-slate-800 bg-slate-900/60 p-6"><div className="flex items-center justify-between"><h2 className="flex items-center gap-2 font-semibold"><KeyRound className="h-5 w-5 text-amber-400" />Integration keys</h2><button onClick={() => rotateMutation.mutate()} className="rounded-lg border border-slate-700 px-3 py-2 text-xs">Rotate · 24h grace</button></div>{issuedSecret && <div className="mt-4 rounded-xl border border-amber-500/30 bg-amber-500/10 p-4"><p className="text-xs font-semibold text-amber-300">Copy now—this secret cannot be retrieved again.</p><div className="mt-2 flex gap-2"><code className="min-w-0 flex-1 break-all text-xs">{issuedSecret}</code><button onClick={() => navigator.clipboard.writeText(issuedSecret)}><Copy className="h-4 w-4" /></button></div></div>}<div className="mt-4 space-y-2">{credentials.data?.map((credential) => <div key={credential.id} className="flex justify-between rounded-lg bg-slate-950 p-3 text-sm"><code>{credential.key_prefix} · v{credential.credential_version}</code><span className="capitalize text-slate-400">{credential.status}</span></div>)}</div></section>
      <section className="rounded-2xl border border-slate-800 bg-slate-900/60 p-6"><h2 className="flex items-center gap-2 font-semibold"><Store className="h-5 w-5 text-violet-400" />Subscription storefront</h2><p className="mt-2 text-sm text-slate-500">Control which active plan is recommended and publish an explicit display order.</p><label className="mt-5 block text-sm">Recommended plan<select value={planUi.data?.recommended_plan_id ?? ''} onChange={(event) => queryClient.setQueryData(['plan-ui', application.id], { ...planUi.data!, recommended_plan_id: event.target.value || null })} className="mt-1 w-full rounded-lg border border-slate-700 bg-slate-950 p-2.5"><option value="">None</option>{plans.data?.filter((plan) => plan.status === 'active').map((plan) => <option key={plan.id} value={plan.id}>{plan.name}</option>)}</select></label><div className="mt-4 space-y-2">{plans.data?.map((plan, index) => <div key={plan.id} className="flex justify-between rounded-lg bg-slate-950 p-3 text-sm"><span>{index + 1}. {plan.name}</span><span className="text-slate-500">{plan.currency} {plan.price}</span></div>)}</div><button onClick={() => storefrontMutation.mutate()} className="mt-5 rounded-lg bg-violet-600 px-4 py-2 text-sm font-semibold">Publish storefront design</button></section></div>
  </div>;
}
