import { useState, type FormEvent } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { CalendarClock, Plus, X } from 'lucide-react';
import { createSubscription, listPlans, listSubscribers, listSubscriptions } from '../../services/controlApi';
import { useAuthStore } from '../../store/authStore';
import { useProductStore } from '../../store/productStore';

const emptyForm = { subscriber_id: '', plan_id: '', external_id: '', coupon_code: '', auto_renews: false };

export function Subscriptions() {
  const application = useProductStore((state) => state.selectedProduct);
  const isOwner = useAuthStore((state) => state.user?.role === 'owner');
  const queryClient = useQueryClient();
  const [showForm, setShowForm] = useState(false);
  const [form, setForm] = useState(emptyForm);
  const subscriptions = useQuery({ queryKey: ['subscriptions', application?.id], queryFn: () => listSubscriptions(application!.id), enabled: Boolean(application) });
  const subscribers = useQuery({ queryKey: ['subscribers', application?.id], queryFn: () => listSubscribers(application!.id), enabled: Boolean(application) });
  const plans = useQuery({ queryKey: ['plans', application?.id], queryFn: () => listPlans(application!.id), enabled: Boolean(application) });
  const mutation = useMutation({ mutationFn: () => createSubscription(application!.id, { ...form, external_id: form.external_id || undefined, coupon_code: form.coupon_code || undefined, coupon_idempotency_key: form.coupon_code ? crypto.randomUUID() : undefined, starts_at: new Date().toISOString() }), onSuccess: async () => { setShowForm(false); setForm(emptyForm); await Promise.all([queryClient.invalidateQueries({ queryKey: ['subscriptions', application?.id] }), queryClient.invalidateQueries({ queryKey: ['coupons', application?.id] }), queryClient.invalidateQueries({ queryKey: ['application-overview', application?.id] })]); } });
  if (!application) return null;
  const activePlans = plans.data?.filter((plan) => plan.status === 'active') ?? [];
  const subscriberNames = new Map(subscribers.data?.map((item) => [item.id, item.name]) ?? []);
  const submit = (event: FormEvent) => { event.preventDefault(); mutation.mutate(); };

  return <div className="mx-auto max-w-6xl space-y-6">
    <header className="flex items-end justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[0.2em] text-blue-400">{application.displayName}</p><h1 className="mt-2 text-3xl font-bold">Subscriptions</h1><p className="mt-2 text-slate-400">Immutable commercial and entitlement snapshots for this application.</p></div>{isOwner && <button onClick={() => setShowForm(true)} disabled={!subscribers.data?.length || !activePlans.length} className="rounded-lg bg-blue-600 px-4 py-2 text-sm font-semibold disabled:opacity-40"><Plus className="mr-2 inline h-4 w-4" />Assign plan</button>}</header>
    {subscriptions.isError && <div className="rounded-xl border border-red-500/20 bg-red-500/10 p-4 text-red-300">Unable to load scoped subscriptions.</div>}
    <div className="grid gap-4">{subscriptions.data?.map((subscription) => <article key={subscription.id} className="flex flex-wrap items-center justify-between gap-5 rounded-2xl border border-slate-800 bg-slate-900/60 p-5"><div className="flex items-center gap-4"><span className="grid h-11 w-11 place-items-center rounded-xl bg-blue-500/10 text-blue-400"><CalendarClock className="h-5 w-5" /></span><div><h2 className="font-semibold">{subscriberNames.get(subscription.subscriber_id) ?? subscription.subscriber_id}</h2><p className="mt-1 text-xs text-slate-500">{subscription.commercial_snapshot.plan_name ?? subscription.commercial_snapshot.plan_code}</p></div></div><div className="text-sm"><p>{subscription.commercial_snapshot.currency} {Number(subscription.commercial_snapshot.final_price ?? subscription.commercial_snapshot.price ?? 0).toLocaleString()}</p>{subscription.commercial_snapshot.coupon_code && <p className="mt-1 text-xs text-emerald-400">{subscription.commercial_snapshot.coupon_code} saved {subscription.commercial_snapshot.currency} {subscription.commercial_snapshot.discount_amount}</p>}<p className="mt-1 text-xs text-slate-500">Ends {subscription.ends_at ? new Date(subscription.ends_at).toLocaleDateString() : 'never'}</p></div><span className="rounded-full bg-emerald-500/10 px-3 py-1 text-xs font-semibold capitalize text-emerald-400">{subscription.status}</span></article>)}{subscriptions.data?.length === 0 && <div className="rounded-2xl border border-dashed border-slate-700 p-8 text-center text-slate-500">No subscriptions have been assigned.</div>}</div>
    {showForm && <div className="fixed inset-0 z-50 grid place-items-center bg-black/70 p-4"><form onSubmit={submit} className="w-full max-w-lg rounded-2xl border border-slate-700 bg-slate-900 p-6"><div className="flex justify-between"><h2 className="text-xl font-semibold">Assign active plan</h2><button type="button" onClick={() => setShowForm(false)}><X className="h-5 w-5" /></button></div><div className="mt-5 grid gap-4"><label className="text-sm">Subscriber<select required value={form.subscriber_id} onChange={(event) => setForm({ ...form, subscriber_id: event.target.value })} className="mt-1 w-full rounded-lg border border-slate-700 bg-slate-950 p-2.5"><option value="">Select subscriber</option>{subscribers.data?.map((item) => <option key={item.id} value={item.id}>{item.name} · {item.external_id}</option>)}</select></label><label className="text-sm">Plan<select required value={form.plan_id} onChange={(event) => setForm({ ...form, plan_id: event.target.value })} className="mt-1 w-full rounded-lg border border-slate-700 bg-slate-950 p-2.5"><option value="">Select active plan</option>{activePlans.map((plan) => <option key={plan.id} value={plan.id}>{plan.name} · {plan.currency} {plan.price}</option>)}</select></label><label className="text-sm">Coupon code (optional)<input value={form.coupon_code} onChange={(event) => setForm({ ...form, coupon_code: event.target.value.toUpperCase() })} className="mt-1 w-full rounded-lg border border-slate-700 bg-slate-950 p-2.5 font-mono uppercase" /></label><label className="text-sm">External subscription ID<input value={form.external_id} onChange={(event) => setForm({ ...form, external_id: event.target.value })} className="mt-1 w-full rounded-lg border border-slate-700 bg-slate-950 p-2.5 font-mono" /></label><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={form.auto_renews} onChange={(event) => setForm({ ...form, auto_renews: event.target.checked })} />Auto-renews</label></div>{mutation.isError && <p className="mt-4 text-sm text-red-300">Assignment failed. Check active subscription and coupon eligibility.</p>}<button className="mt-6 w-full rounded-lg bg-blue-600 py-3 text-sm font-semibold">Assign subscription</button></form></div>}
  </div>;
}
